[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyorchis"
version = "2026.8.0a.0"
description = "General-Use ORCHIDs for Modern Applications & Protocols."
requires-python = ">=3.13"
dependencies = [
    "cryptography>=50.0.0",
    "pycryptodome>3.23.0",
    "jwcrypto>=1.5.8",
    "cwt>=3.3.0",
]
authors = [
    { name = "Adam Wiethuechter", email = "adam.wiethuechter@gmail.com" }
]
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["COPYING.txt"]
keywords = [
    "orchid", "cose", "cose-sign", "cose-sign1", "jose", "jwk", "jws", "hip", "drip", "rfc7401", "rfc9374", "rfc7343"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications", "Topic :: Internet", "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Networking"
]

[project.urls]
Repository = "https://github.com/kc2rxo/orchis.git"