[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyblossom"
version = "0.1.0"
description = "Overlay Routable Cryptographic Hash IDentifier library for modern applications & protocols."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
    { name = "Adam Wiethuechter", email = "atw.ietf@gmail.com" }
]
dependencies = [
    "cryptography>=50.0.0",
    "pycryptodome>3.23.0",
    "jwcrypto>=1.5.8",
    "cwt>=3.3.0",
]